disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Carnivuth's dotfiles"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = ""
  # secondaryLogo = "img/secondary-logo.png"
  description = "Scripts and dotfiles documentation"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Matteo Longhi"
   email = "matti200042@gmail.com"
   image = "avatar.jpg"
   imageQuality = 96
   headline = "homelab addicted guy with a passion for Music and dogs"
   bio = " I'm a software engineer with a passion for Music, food, dogs, videogames and open source software, i'm currently working as a devops engineer"
   links = [
     { email = "mailto:matti200042@gmail.com" },
     { link = "https://www.carnivuth.org/" },
     { github = "https://github.com/carnivuth" },
     { instagram = "https://instagram.com/longhi.matteo" },
     { linkedin = "https://linkedin.com/in/matteo-longhi-b3a433247" },
   ]
