hl.env("XCURSOR_SIZE","24")
hl.env("QT_QPA_PLATFORMTHEME","gtk3")
hl.env("XDG_SESSION_TYPE","wayland")
hl.env("DESKTOP_SESSION","hyprland")
hl.env("EDITOR","nvim")
hl.env("MENU_BACKEND","bemenu -p")
hl.env("GDK_SCALE","2")
hl.env("TERM","alacritty")
hl.env("TERMINAL_CMD","alacritty -e")
hl.env("FLOATING_TERMINAL_CMD","alacritty --class floating -e")
hl.env("ELECTRON_OZONE_PLATFORM_HINT","wayland")
hl.env( "BEMENU_OPTS","--fb '#24273a' --ff '#cad3f5' --nb '#24273a' --nf '#cad3f5' --tb '#24273a' --hb '#24273a' --tf '#ed8796' --hf '#eed49f' --af '#cad3f5' --ab '#24273a' --bdr '#b4befe' --hp 10 -B 1 --fn 'JetBrainsMono Nerd Font,JetBrainsMono NF:style=ExtraBold 10' -H 30")
hl.env("PATH"," /home/matteo/.local/share/nvim/mason/bin:/home/matteo/.local/bin:/home/matteo/.local/bin:/home/matteo/.local/bin:/home/matteo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl")
