exec-once = hyprpaper &
exec-once = udiskie &
exec-once = $bin/caffeine.sh off
exec-once = waybar &
exec-once = nm-applet &
exec-once = blueman-applet &
exec-once = dunst &
exec-once = thunderbird &
exec-once = nextcloud &
exec-once = Telegram -startintray &
exec-once = bw sync &
exec-once = wl-paste --watch cliphist store
exec-once = systemctl --user start hyprpolkitagent
