"$schema" = 'https://starship.rs/config-schema.json'
format = '''
[┌](bold green) $username@$hostname:$directory$git_branch$golang
[└─>](bold green) '''

add_newline = false

[cmd_duration]
disabled = true

[hostname]
ssh_only = false
format ='[$hostname]($style)'

[vagrant]
disabled = true

[username]
show_always = true
format ='[$user]($style)'
